### ISSUE TITLE
Incorrect handling of parameters

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/translator-message-gettext#19]
### What steps will reproduce the problem?
`echo $t->translate('Sign in successful - {date}', ['date' => date('Y-m-d G:i:s')], 'user');`

### What is the expected result?
`Sign in successful - 2021-01-16 13:37:42`

### What do you get instead?
```
TypeError: dngettext(): Argument #4 ($count) must be of type int, string given in /yii3/vendor/yiisoft/translator-message-gettext/src/MessageSource.php:35
Stack trace:
#0 /yii3/vendor/yiisoft/translator-message-gettext/src/MessageSource.php(35): dngettext()
#1 /yii3/vendor/yiisoft/translator/src/Category.php(42): Yiisoft\Translator\Message\Gettext\MessageSource->getMessage()
#2 /yii3/vendor/yiisoft/translator/src/Translator.php(92): Yiisoft\Translator\Category->getMessage()
#3 /yii3/mister42/Control/site/index.php(19): Yiisoft\Translator\Translator->translate()
#4 /yii3/vendor/yiisoft/view/src/PhpTemplateRenderer.php(13): require('...')
#5 /yii3/vendor/yiisoft/view/src/PhpTemplateRenderer.php(20): Yiisoft\View\PhpTemplateRenderer->Yiisoft\View\{closure}()
#6 /yii3/vendor/yiisoft/view/src/View.php(361): Yiisoft\View\PhpTemplateRenderer->render()
#7 /yii3/vendor/yiisoft/view/src/View.php(264): Yiisoft\View\View->renderFile()
#8 /yii3/vendor/yiisoft/yii-view/src/ViewRenderer.php(193): Yiisoft\View\View->render()
#9 /yii3/vendor/yiisoft/yii-view/src/ViewRenderer.php(74): Yiisoft\Yii\View\ViewRenderer->renderProxy()
#10 /yii3/vendor/yiisoft/data-response/src/DataResponse.php(163): Yiisoft\Yii\View\ViewRenderer->Yiisoft\Yii\View\{closure}()
#11 /yii3/vendor/yiisoft/data-response/src/Formatter/HtmlDataResponseFormatter.php(29): Yiisoft\DataResponse\DataResponse->getData()
#12 /yii3/vendor/yiisoft/data-response/src/DataResponse.php(179): Yiisoft\DataResponse\Formatter\HtmlDataResponseFormatter->format()
#13 /yii3/vendor/yiisoft/data-response/src/DataResponse.php(40): Yiisoft\DataResponse\DataResponse->formatResponse()
#14 /yii3/vendor/yiisoft/yii-web/src/SapiEmitter.php(101): Yiisoft\DataResponse\DataResponse->getBody()
#15 /yii3/vendor/yiisoft/yii-web/src/SapiEmitter.php(40): Yiisoft\Yii\Web\SapiEmitter->shouldOutputBody()
#16 /yii3/webroot/index.php(59): Yiisoft\Yii\Web\SapiEmitter->emit()
#17 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 8.0.1
| Operating system | Debian 10

**Comment by samdark** [comment]
Still an issue or was fixed?

**Comment by darkdef** [comment]
Fixed
